// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxO1o42qG5kBl68vYqzlKN1VrMQOn2hU',
    appId: '1:225501447717:web:ec75250269e33251a721cc',
    messagingSenderId: '225501447717',
    projectId: 'personal-project-4e389',
    authDomain: 'personal-project-4e389.firebaseapp.com',
    storageBucket: 'personal-project-4e389.appspot.com',
    measurementId: 'G-XMQGSRLVQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0Ot6ks85wQ9-CIeRFiyw0XLjv-HQjuc',
    appId: '1:225501447717:android:c3be8b2c3ca15b88a721cc',
    messagingSenderId: '225501447717',
    projectId: 'personal-project-4e389',
    storageBucket: 'personal-project-4e389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMpc6h8xZ66KjUPY-Lv0S0jDRtVVhmGb8',
    appId: '1:225501447717:ios:6a4cb64f54ae0f0da721cc',
    messagingSenderId: '225501447717',
    projectId: 'personal-project-4e389',
    storageBucket: 'personal-project-4e389.appspot.com',
    iosBundleId: 'com.example.personalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMpc6h8xZ66KjUPY-Lv0S0jDRtVVhmGb8',
    appId: '1:225501447717:ios:a29c7007b8d1d914a721cc',
    messagingSenderId: '225501447717',
    projectId: 'personal-project-4e389',
    storageBucket: 'personal-project-4e389.appspot.com',
    iosBundleId: 'com.example.personalProject.RunnerTests',
  );
}
